import Link from 'next/link'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <nav className="h-24 flex  w-full bg-backgroundSecondary">
      <Link  className="items-center flex font-bold text-3xl ml-10" href="/">
    HELP-DESK
</Link>
               </nav>
        <main className="min-h-screen bg-background  items-center">
       
          {children}
        </main>
      </body>
    </html>
  )
}
